ACCOUNTS=[
"GA7UJMQTU6W36COR57SMGGUH66MORHHHHVX4WRQ7YOD2D724MTGBK3D7"
]

VERSION="1.0.0"

[DOCUMENTATION]
ORG_NAME="eastellar"
ORG_URL="https://www.eastellar.com/"
ORG_LOGO="https://www.eastellar.com/images/eastellar.png"
ORG_OFFICIAL_EMAIL="mail@eastellar.com"
ORG_TWITTER="eastellar"
ORG_DESCRIPTION="eastellar.com is a Stellar Assets Marketplace"

[[CURRENCIES]]
code="MOBI"
issuer="GASPHHE2ZUYTYZCXBK24LRXBGJIMS3TEL27Q7JPYAL322VYOKXGHBFWZ"
status="live"
display_decimals=4
name="MOBI"
fixed_number=25000000000
desc="MOBI is issued by SupremeStellar Team."
conditions="Maximum supply of MOBI is 25B tokens only"
image="https://supremestellar.com/images/MOBI.png"
