VERSION="2.5.0"

[DOCUMENTATION]
ORG_NAME="eastellar"
ORG_URL="https://www.eastellar.com/"
ORG_LOGO="https://www.eastellar.com/images/eastellar.png"
ORG_DESCRIPTION="eastellar.com searches Minting Materials from The East. Eastellar utilize the stellar blockchain technology to mint some of the rarest token and one of many that you have been familiar with. We improve collecting and trade experience with automated and digitalization all operations cycle with ease.Before you begin trading foreign exchange, cryptocurrencies, or any other assets. Please consider your investment capital experience in trading, and risk tolerance"

[[CURRENCIES]]
code="MOBI"
issuer="GASPHHE2ZUYTYZCXBK24LRXBGJIMS3TEL27Q7JPYAL322VYOKXGHBFWZ"
status="live"
display_decimals=4
name="MOBI"
fixed_number=25000000000
desc="MOBI is issued by Eastellar Team."
conditions="Maximum supply of MOBI is 25B tokens only"
image="https://eastellar.com/images/MOBI.png"
