ACCOUNTS=[
"GA7UJMQTU6W36COR57SMGGUH66MORHHHHVX4WRQ7YOD2D724MTGBK3D7"
]

VERSION="1.0.0"

[DOCUMENTATION]
ORG_NAME="eastellar"
ORG_URL="https://www.eastellar.com/"
ORG_LOGO="https://www.eastellar.com/images/eastellar.png"
ORG_OFFICIAL_EMAIL="mail@eastellar.com"
ORG_TWITTER="eastellar"
ORG_DESCRIPTION="eastellar.com is a Stellar Assets Marketplace"

[[CURRENCIES]]
code="MOBI"
issuer="GASPHHE2ZUYTYZCXBK24LRXBGJIMS3TEL27Q7JPYAL322VYOKXGHBFWZ"
status="live"
display_decimals=4
name="MOBI"
fixed_number=25000000000
desc="MOBI is issued by Eastellar Team."
conditions="Maximum supply of MOBI is 25B tokens only"
image="https://eastellar.com/images/MOBI.png"

[[CURRENCIES]]
code="ETH"
issuer="GC6PSOITVG5KWEX65IATGG5YSBVAIWTXBRGFBQYXDXCRYRPBWLATVUAZ"
status="live"
display_decimals=4
name="ETH"
fixed_number=25000000000
desc="ETH is issued by Eastellar Team."
conditions="Maximum supply of ETH is 25B tokens only"
image="https://eastellar.com/images/ETH.png"

[[CURRENCIES]]
code="BTC"
issuer="GAJNJXDW5RLA2A4UXIBKYHL3FVZSFNBIYHEYTL4BGPOOF2HKVMG3BOYE"
status="live"
display_decimals=4
name="BTC"
fixed_number=25000000000
desc="BTC is issued by Eastellar Team."
conditions="Maximum supply of BTC is 25B tokens only"
image="https://eastellar.com/images/BTC.png"

[[CURRENCIES]]
code="USDT"
issuer="GB4KYMYHJZ4JLKBRMD7UFOIFQKGXB67CUE2SV2YUVGUTQ3NE2JCEA5JD"
status="live"
display_decimals=4
name="USDT"
fixed_number=25000000000
desc="USDT is issued by Eastellar Team."
conditions="Maximum supply of USDT is 25B tokens only"
image="https://eastellar.com/images/USDT.png"
