ACCOUNTS=[
"GA7UJMQTU6W36COR57SMGGUH66MORHHHHVX4WRQ7YOD2D724MTGBK3D7"
]

VERSION="1.0.0"

[DOCUMENTATION]
ORG_NAME="eastellar"
ORG_URL="https://www.eastellar.com/"
ORG_LOGO="https://www.eastellar.com/images/eastellar.png"
ORG_OFFICIAL_EMAIL="mail@eastellar.com"
ORG_TWITTER="eastellar"
ORG_DESCRIPTION="eastellar.com searches Minting Materials from The East. Eastellar utilize the stellar blockchain technology to mint some of the rarest token and one of many that you have been familiar with. We improve collecting and trade experience with automated and digitalization all operations cycle with ease.Before you begin trading foreign exchange, cryptocurrencies, or any other assets. Please consider your investment capital experience in trading, and risk tolerance"

[[CURRENCIES]]
code="MOBI"
issuer="GASPHHE2ZUYTYZCXBK24LRXBGJIMS3TEL27Q7JPYAL322VYOKXGHBFWZ"
status="live"
display_decimals=4
name="MOBI"
fixed_number=25000000000
desc="MOBI is issued by Eastellar Team."
conditions="Maximum supply of MOBI is 25B tokens only"
image="https://eastellar.com/images/MOBI.png"

[[CURRENCIES]]
code="ETH"
issuer="GC6PSOITVG5KWEX65IATGG5YSBVAIWTXBRGFBQYXDXCRYRPBWLATVUAZ"
status="live"
display_decimals=4
name="ETH"
fixed_number=25000000000
desc="ETH is issued by Eastellar Team."
conditions="Maximum supply of ETH is 25B tokens only"
image="https://eastellar.com/images/ETH.png"

[[CURRENCIES]]
code="BTC"
issuer="GAJNJXDW5RLA2A4UXIBKYHL3FVZSFNBIYHEYTL4BGPOOF2HKVMG3BOYE"
status="live"
display_decimals=4
name="BTC"
fixed_number=25000000000
desc="BTC is issued by Eastellar Team."
conditions="Maximum supply of BTC is 25B tokens only"
image="https://eastellar.com/images/BTC.png"

[[CURRENCIES]]
code="USDT"
issuer="GB4KYMYHJZ4JLKBRMD7UFOIFQKGXB67CUE2SV2YUVGUTQ3NE2JCEA5JD"
status="live"
display_decimals=4
name="USDT"
fixed_number=25000000000
desc="USDT is issued by Eastellar Team."
conditions="Maximum supply of USDT is 25B tokens only"
image="https://eastellar.com/images/USDT.png"

[[CURRENCIES]]
code="XRP"
issuer="GAFMMGOZ4WEO36D2RDZLJCBR563YPC4TRBAZAWLN3SAZKMZM2IJO7MP7"
status="live"
display_decimals=4
name="XRP"
fixed_number=25000000000
desc="XRP is issued by Eastellar Team."
conditions="Maximum supply of XRP is 25B tokens only"
image="https://eastellar.com/images/XRP.png"

[[CURRENCIES]]
code="USDC"
issuer="GDIQVO2M33IJUNUOI4QHFKKLAYLNGT5QKPM5ZK77GRI5UT553PSPUPRK"
status="live"
display_decimals=4
name="USDC"
fixed_number=25000000000
desc="USDC is issued by Eastellar Team."
conditions="Maximum supply of USDC is 25B tokens only"
image="https://eastellar.com/images/USDC.png"

[[CURRENCIES]]
code="LIGHTHOUSE"
issuer="GAWYEFUBF2ECZGMU4TP22IQXMGRBJAMRZEBSHBB6O3PP7VQC7DLVKDUU"
status="live"
display_decimals=4
name="LIGHTHOUSE"
fixed_number=25000000000
desc="LIGHTHOUSE is issued by Eastellar Team."
conditions="Maximum supply of LIGHTHOUSE is 25B tokens only"
image="https://eastellar.com/images/LIGHTHOUSE.png"

[[CURRENCIES]]
code="HORSE"
issuer="GBNXX3KZDY6QZTCP5QLN6NE33WMDVZHL4G3S5NUW2OMAD67KION6GEES"
status="live"
display_decimals=4
name="HORSE"
fixed_number=25000000000
desc="HORSE is issued by Eastellar Team."
conditions="Maximum supply of HORSE is 25B tokens only"
image="https://eastellar.com/images/HORSE.png"

[[CURRENCIES]]
code="WIFI"
issuer="GABVF5DRC4VZQQASPZFSJE4MG3WBQPVKVKWUPLHQ4HTK3EOR7FDX7T6F"
status="live"
display_decimals=4
name="WIFI"
fixed_number=50000000000
desc="WIFI is issued by Eastellar Team."
conditions="Maximum supply of WIFI is 50B tokens only"
image="https://eastellar.com/images/WIFI.png"

[[CURRENCIES]]
code="COSMIC"
issuer="GDOGXSYJ4DNQVGINJ5NTDHLRHPZCAABULQABIODOK7KJUEM5Y72TIUEA"
status="live"
display_decimals=4
name="COSMIC"
fixed_number=50000000000
desc="COSMIC is issued by Eastellar Team."
conditions="Maximum supply of COSMIC is 50B tokens only"
image="https://eastellar.com/images/COSMIC.png"

[[CURRENCIES]]
code="MAP"
issuer="GBMD4K6MCHJ7LQDVB4WXXNUAJS5APTKXZE3UNYYWGLQBJAEAE6PAKRHL"
status="live"
display_decimals=4
name="MAP"
fixed_number=50000000000
desc="MAP is issued by Eastellar Team."
conditions="Maximum supply of MAP is 50B tokens only"
image="https://eastellar.com/images/MAP.png"

[[CURRENCIES]]
code="CIRCLE"
issuer="GA52EFKZU5CUZMLRDURUBXYCMXTJLGF2NX32PJY23M47Q6F6SJYZPEE3"
status="live"
display_decimals=4
name="CIRCLE"
fixed_number=50000000000
desc="CIRCLE is issued by Eastellar Team."
conditions="Maximum supply of CIRCLE is 50B tokens only"
image="https://eastellar.com/images/CIRCLE.png"

[[CURRENCIES]]
code="PIXEL"
issuer="GCOHRHDM6M5CCJ46UPQ4XWU3T7ZQ223UNGDSVSUORAIHSI5BYHV5K7MS"
status="live"
display_decimals=4
name="PIXEL"
fixed_number=25000000000
desc="PIXEL is issued by Eastellar Team."
conditions="Maximum supply of PIXEL is 25B tokens only"
image="https://eastellar.com/images/PIXEL.png"

[[CURRENCIES]]
code="ONE"
issuer="GB7ZDXTZXIQSB2CHT4QR4EGJXNOLLOWFPFHAJOH3FWQCT4GIWZ2YXID4"
status="live"
display_decimals=4
name="ONE"
fixed_number=25000000000
desc="ONE is issued by Eastellar Team."
conditions="Maximum supply of ONE is 25B tokens only"
image="https://eastellar.com/images/ONE.png"

[[CURRENCIES]]
code="TELESCOPE"
issuer="GDQ7AA2LCQAFH7S46OD4WPM6WMX5PUXMD533VSQMP2AS6ZPGTRQLWBFX"
status="live"
display_decimals=4
name="TELESCOPE"
fixed_number=25000000000
desc="TELESCOPE is issued by Eastellar Team."
conditions="Maximum supply of TELESCOPE is 25B tokens only"
image="https://eastellar.com/images/TELESCOPE.png"

[[CURRENCIES]]
code="TWO"
issuer="GBQDV6JQOYDZ3CZTRWR4F4V56Z2X64AB54D4WLZ5R56M3ZP5XQ3ABVW2"
status="live"
display_decimals=4
name="TWO"
fixed_number=25000000000
desc="TWO is issued by Eastellar Team."
conditions="Maximum supply of TWO is 25B tokens only"
image="https://eastellar.com/images/TWO.png"

[[CURRENCIES]]
code="GROWTH"
issuer="GA4I6JD2LAAGL7TVCJP744ZGG27NPYEHHSODXX52YYKQBE3KWXVM6XF6"
status="live"
display_decimals=4
name="GROWTH"
fixed_number=25000000000
desc="GROWTH is issued by Eastellar Team."
conditions="Maximum supply of GROWTH is 25B tokens only"
image="https://eastellar.com/images/GROWTH.png"

[[CURRENCIES]]
code="THREE"
issuer="GCIFIT7JB3TSFAP53RNL7G6BPZQGNWU4T4ECGO7XVOWP57LWDFJNXMBM"
status="live"
display_decimals=4
name="THREE"
fixed_number=25000000000
desc="THREE is issued by Eastellar Team."
conditions="Maximum supply of THREE is 25B tokens only"
image="https://eastellar.com/images/THREE.png"

[[CURRENCIES]]
code="CROWN"
issuer="GAVEFSSCCHWQYZZEKLFGBOKVQUGVO26XEAWNDWH53XH24U6576PK3TUG"
status="live"
display_decimals=4
name="CROWN"
fixed_number=25000000000
desc="CROWN is issued by Eastellar Team."
conditions="Maximum supply of CROWN is 25B tokens only"
image="https://eastellar.com/images/CROWN.png"

[[CURRENCIES]]
code="FOUR"
issuer="GCODENLNW6SQREVH3QTVN3EF6RJ5Q6C2RVBXQBATBCUG36YDNFZPNWZN"
status="live"
display_decimals=4
name="FOUR"
fixed_number=25000000000
desc="FOUR is issued by Eastellar Team."
conditions="Maximum supply of FOUR is 25B tokens only"
image="https://eastellar.com/images/FOUR.png"

[[CURRENCIES]]
code="CAPTAIN"
issuer="GCUMCUR6OOWWYC3JJFIWAITYJF3TNEKRENKYRW2VT4X5ST7L7VAKUY3Y"
status="live"
display_decimals=4
name="CAPTAIN"
fixed_number=25000000000
desc="CAPTAIN is issued by Eastellar Team."
conditions="Maximum supply of CAPTAIN is 25B tokens only"
image="https://eastellar.com/images/CAPTAIN.png"

[[CURRENCIES]]
code="KOALA"
issuer="GA54TNIEJTWQN7QH5N7NESV3XSTMXZBUBFUAFJPCZQBXYBGLZKKKFYHC"
status="live"
display_decimals=4
name="KOALA"
fixed_number=25000000000
desc="KOALA is issued by Eastellar Team."
conditions="Maximum supply of KOALA is 25B tokens only"
image="https://eastellar.com/images/KOALA.png"

[[CURRENCIES]]
code="FIVE"
issuer="GB2KAGTNNUYMHEFPVNZIRCM45XTM3GH3LRKYYW5BWQ2E6ZIDW3BS6ZBF"
status="live"
display_decimals=4
name="FIVE"
fixed_number=25000000000
desc="FIVE is issued by Eastellar Team."
conditions="Maximum supply of FIVE is 25B tokens only"
image="https://eastellar.com/images/FIVE.png"

[[CURRENCIES]]
code="ARROW"
issuer="GA6IBKNWVN7KTEIZR2Z3WCUOUQEUUI6B4LCPXO6KOV266LP3Q6SJLJY3"
status="live"
display_decimals=4
name="ARROW"
fixed_number=25000000000
desc="ARROW is issued by Eastellar Team."
conditions="Maximum supply of ARROW is 25B tokens only"
image="https://eastellar.com/images/ARROW.png"

[[CURRENCIES]]
code="TULIPEPE"
issuer="GDLW73H2BLCNKXWSYZKJ5MYCPZYRA7I3PUB64IWWR4PJVXGIJGTDJECK"
status="live"
display_decimals=4
name="TULIPEPE"
fixed_number=25000000000
desc="TULIPEPE is issued by Eastellar Team."
conditions="Maximum supply of TULIPEPE is 25B tokens only"
image="https://eastellar.com/images/TULIPEPE.png"

[[CURRENCIES]]
code="SWOT"
issuer="GDUHHLQZ7HYFLS5ZY7CJIMQYL6TDQ5LLNMAKIJD5TSFFWYOZJZ7MXXF6"
status="live"
display_decimals=4
name="SWOT"
fixed_number=25000000000
desc="SWOT is issued by Eastellar Team."
conditions="Maximum supply of SWOT is 25B tokens only"
image="https://eastellar.com/images/SWOT.png"

[[CURRENCIES]]
code="RAPEPE"
issuer="GAO3TQIBXFZRPVGH2PUX24BQYFIJ466THV6OLC3AEQSNWYFHDPBEBOXM"
status="live"
display_decimals=4
name="RAPEPE"
fixed_number=25000000000
desc="RAPEPE is issued by Eastellar Team."
conditions="Maximum supply of RAPEPE is 25B tokens only"
image="https://eastellar.com/images/RAPEPE.png"

[[CURRENCIES]]
code="SIGNAL"
issuer="GCB4MYKQJL2RIHQAIW52LMIQONJ7AZ44GPDY6UUQLS2GN2GNLW3IIIHH"
status="live"
display_decimals=4
name="SIGNAL"
fixed_number=25000000000
desc="SIGNAL is issued by Eastellar Team."
conditions="Maximum supply of SIGNAL is 25B tokens only"
image="https://eastellar.com/images/SIGNAL.png"

[[CURRENCIES]]
code="HAND"
issuer="GCBKYCR6O4A5BRFM6O6F4D7FJHUNYRKQGVTLQZIVUKJIHHJXM5TJMC2Z"
status="live"
display_decimals=4
name="HAND"
fixed_number=25000000000
desc="HAND is issued by Eastellar Team."
conditions="Maximum supply of HAND is 25B tokens only"
image="https://eastellar.com/images/HAND.png"

[[CURRENCIES]]
code="BICEPEPE"
issuer="GB7XBL4MLFPFLKVESFE4GAN7W2LTEUKKHFIVZ4V3BZDHK4BN4FQYDPOQ"
status="live"
display_decimals=4
name="BICEPEPE"
fixed_number=25000000000
desc="BICEPEPE is issued by Eastellar Team."
conditions="Maximum supply of BICEPEPE is 25B tokens only"
image="https://eastellar.com/images/BICEPEPE.png"

[[CURRENCIES]]
code="BLEEPEPE"
issuer="GDA3EAUYMGS4A67MEMFGHST7D47QAILSEPZLBYCZPWRFWHUZJ55JO5HY"
status="live"
display_decimals=4
name="BLEEPEPE"
fixed_number=25000000000
desc="BLEEPEPE is issued by Eastellar Team."
conditions="Maximum supply of BLEEPEPE is 25B tokens only"
image="https://eastellar.com/images/BLEEPEPE.png"

[[CURRENCIES]]
code="COOKIES"
issuer="GA6VTYQLELCNK5WMT3ENAFD4B7CBFRUOW7UEZ4CZ7GCTGFW353QLC5NH"
status="live"
display_decimals=4
name="COOKIES"
fixed_number=25000000000
desc="COOKIES is issued by Eastellar Team."
conditions="Maximum supply of COOKIES is 25B tokens only"
image="https://eastellar.com/images/COOKIES.png"

[[CURRENCIES]]
code="BEEPEPE"
issuer="GB2TC4OHPHFTKNXSHTZ24OCCROGJLY53K6IMBTWWMSYZRVZKAWFXMDFT"
status="live"
display_decimals=4
name="BEEPEPE"
fixed_number=25000000000
desc="BEEPEPE is issued by Eastellar Team."
conditions="Maximum supply of BEEPEPE is 25B tokens only"
image="https://eastellar.com/images/BEEPEPE.png"

[[CURRENCIES]]
code="POSITIVE"
issuer="GDQWVLD3EE5KU4XSCFBHF6WQ7EB7W67QHOWPBDTCXTEJHPUDEUCLDUKH"
status="live"
display_decimals=4
name="POSITIVE"
fixed_number=25000000000
desc="POSITIVE is issued by Eastellar Team."
conditions="Maximum supply of POSITIVE is 25B tokens only"
image="https://eastellar.com/images/POSITIVE.png"

[[CURRENCIES]]
code="zXLM"
issuer="GABVRXHJTDBMDKSOFBDOKEZFFDMR7K6DQPMRLSNY2GHZH52B7N3LEQCM"
status="live"
display_decimals=4
name="zXLM"
fixed_number=25000000000
desc="zXLM is issued by Eastellar Team."
conditions="Maximum supply of zXLM is 25B tokens only"
image="https://eastellar.com/images/zXLM.png"

[[CURRENCIES]]
code="AUTUMN"
issuer="GC4UIWMGYKUYHSI25NI5OQ2OVNQ6D6S53FKYNELBUPTBHCWIXVQDUBKW"
status="live"
display_decimals=4
name="AUTUMN"
fixed_number=25000000000
desc="AUTUMN is issued by Eastellar Team."
conditions="Maximum supply of AUTUMN is 25B tokens only"
image="https://eastellar.com/images/AUTUMN.png"

[[CURRENCIES]]
code="zBTC"
issuer="GCBAIA7NGAJO5U46P5BTHRHXA45VI3TMZZ225Y44GJRFKZXLZCFHBYJO"
status="live"
display_decimals=4
name="zBTC"
fixed_number=25000000000
desc="zBTC is issued by Eastellar Team."
conditions="Maximum supply of zBTC is 25B tokens only"
image="https://eastellar.com/images/zBTC.png"

[[CURRENCIES]]
code="LILAC"
issuer="GCYOYYYJ4SDJFNNG3PGRLFWVRZADPMWJASGYDG6DAIWVAWT535JQN5Q5"
status="live"
display_decimals=4
name="LILAC"
fixed_number=25000000000
desc="LILAC is issued by Eastellar Team."
conditions="Maximum supply of LILAC is 25B tokens only"
image="https://eastellar.com/images/LILAC.png"

[[CURRENCIES]]
code="zXRP"
issuer="GC3RNJFIFBRGNQEOO3GISX2KLBHQAJ7T74J4JX2IFCQR3JNYSMEGOJK4"
status="live"
display_decimals=4
name="zXRP"
fixed_number=25000000000
desc="zXRP is issued by Eastellar Team."
conditions="Maximum supply of zXRP is 25B tokens only"
image="https://eastellar.com/images/zXRP.png"

[[CURRENCIES]]
code="RAIN"
issuer="GDJ74KLQCYAIQKXHBKZEDCPBVW2BXGU7AAK6DO2WRKRJR3XSBJMKG2LA"
status="live"
display_decimals=4
name="RAIN"
fixed_number=25000000000
desc="RAIN is issued by Eastellar Team."
conditions="Maximum supply of RAIN is 25B tokens only"
image="https://eastellar.com/images/RAIN.png"

[[CURRENCIES]]
code="zETH"
issuer="GCBDAOKZ4QNZOHLH264C5NVWIPVBVVP2X6SSEDKS7X3EUL36Y4DJVS7Z"
status="live"
display_decimals=4
name="zETH"
fixed_number=25000000000
desc="zETH is issued by Eastellar Team."
conditions="Maximum supply of zETH is 25B tokens only"
image="https://eastellar.com/images/zETH.png"

[[CURRENCIES]]
code="COOL"
issuer="GB3QUOKE674BIEEG3SNQCGUZOM7KP3EBTNP4ZRFJ7QIWK5FPSRG2JC44"
status="live"
display_decimals=4
name="COOL"
fixed_number=25000000000
desc="COOL is issued by Eastellar Team."
conditions="Maximum supply of COOL is 25B tokens only"
image="https://eastellar.com/images/COOL.png"

[[CURRENCIES]]
code="zUSD"
issuer="GAQLH5PIARNOCWLKWPDMO3DB7QU6EE23MILWBCDRHXJD2YZ344TYG5NE"
status="live"
display_decimals=4
name="zUSD"
fixed_number=25000000000
desc="zUSD is issued by Eastellar Team."
conditions="Maximum supply of zUSD is 25B tokens only"
image="https://eastellar.com/images/zUSD.png"

[[CURRENCIES]]
code="ROCKET"
issuer="GBSKMLIQD5COX76T6TVDDWYVQE2EXR4DLMWQFYOKIO7NQGRRLR7NRXUB"
status="live"
display_decimals=4
name="ROCKET"
fixed_number=25000000000
desc="ROCKET is issued by Eastellar Team."
conditions="Maximum supply of ROCKET is 25B tokens only"
image="https://eastellar.com/images/ROCKET.png"

[[CURRENCIES]]
code="aquaZ"
issuer="GDX4RMBOVVVSZVQPCRYI37B627XHL6NBAWLSSWORPMKWWRH24E2ZOCW6"
status="live"
display_decimals=4
name="aquaZ"
fixed_number=25000000000
desc="aquaZ is issued by Eastellar Team."
conditions="Maximum supply of aquaZ is 25B tokens only"
image="https://eastellar.com/images/aquaZ.png"

[[CURRENCIES]]
code="SHARK"
issuer="GATAV6OGQRFXDGH6O62NMD3Z4J2AD7ZGCTBZYK6BACBIPZGVAAM5NW46"
status="live"
display_decimals=4
name="SHARK"
fixed_number=25000000000
desc="SHARK is issued by Eastellar Team."
conditions="Maximum supply of SHARK is 25B tokens only"
image="https://eastellar.com/images/SHARK.png"

[[CURRENCIES]]
code="USDz"
issuer="GBAWASYNP7L2P3HBC73RSSUPOALWPJJSIZF3DV27KRZMMGUAO4XD6US2"
status="live"
display_decimals=4
name="USDz"
fixed_number=25000000000
desc="USDz is issued by Eastellar Team."
conditions="Maximum supply of USDz is 25B tokens only"
image="https://eastellar.com/images/USDz.png"

[[CURRENCIES]]
code="ANT"
issuer="GDDYHU7WVC2TK7LKIZJPAOL5C5H2VBKTQP5Y4ZOKQ3A7FIGBKIJD7EDJ"
status="live"
display_decimals=4
name="ANT"
fixed_number=25000000000
desc="ANT is issued by Eastellar Team."
conditions="Maximum supply of ANT is 25B tokens only"
image="https://eastellar.com/images/ANT.png"

[[CURRENCIES]]
code="SHXz"
issuer="GDJEBKV4QUUFZNZ4DE53RZANU5P7XJZVGA6EY5DIU67M37TBXWOEJHMC"
status="live"
display_decimals=4
name="SHXz"
fixed_number=25000000000
desc="SHXz is issued by Eastellar Team."
conditions="Maximum supply of SHXz is 25B tokens only"
image="https://eastellar.com/images/SHXz.png"

[[CURRENCIES]]
code="FAIRY"
issuer="GDU4ALGUCDMZONB7TSIN63UE3ETGV6UX34WSJJFVP4QVOQHRDLWXONK3"
status="live"
display_decimals=4
name="FAIRY"
fixed_number=25000000000
desc="FAIRY is issued by Eastellar Team."
conditions="Maximum supply of FAIRY is 25B tokens only"
image="https://eastellar.com/images/FAIRY.png"

[[CURRENCIES]]
code="zADA"
issuer="GBMSFRYP7ZQI4B5ENJI4AM3OTFSCWAOVTFGW3T2PE4VMVNV4MMAFWLT2"
status="live"
display_decimals=4
name="zADA"
fixed_number=25000000000
desc="zADA is issued by Eastellar Team."
conditions="Maximum supply of zADA is 25B tokens only"
image="https://eastellar.com/images/zADA.png"

[[CURRENCIES]]
code="TURTLE"
issuer="GALQKHMP4OARIMILCCNS5D6GWQRQZVFJB7SYOLFCMBBOSX2MAYEM3O75"
status="live"
display_decimals=4
name="TURTLE"
fixed_number=25000000000
desc="TURTLE is issued by Eastellar Team."
conditions="Maximum supply of TURTLE is 25B tokens only"
image="https://eastellar.com/images/TURTLE.png"

[[CURRENCIES]]
code="OREGANO"
issuer="GBE5DGXKL37G5YTD5LXAN5I4XBBOPIID7LGK5JLI6Q7XY2FFLACCP6G3"
status="live"
display_decimals=4
name="OREGANO"
fixed_number=25000000000
desc="OREGANO is issued by Eastellar Team."
conditions="Maximum supply of OREGANO is 25B tokens only"
image="https://eastellar.com/images/OREGANO.png"

[[CURRENCIES]]
code="RESIDENCE"
issuer="GCVUEL2ROI7NKMQ7FBAHXRFG73MVHSTHPRBGUJQBVICXPUZS7YMJOXI5"
status="live"
display_decimals=4
name="RESIDENCE"
fixed_number=25000000000
desc="RESIDENCE is issued by Eastellar Team."
conditions="Maximum supply of RESIDENCE is 25B tokens only"
image="https://eastellar.com/images/RESIDENCE.png"

[[CURRENCIES]]
code="MINT"
issuer="GCRECF3X3YNUJKLCGZNDU7QWZQEYLNWWWNP2YNECLBC2XXQH23GDO6TT"
status="live"
display_decimals=4
name="MINT"
fixed_number=25000000000
desc="MINT is issued by Eastellar Team."
conditions="Maximum supply of MINT is 25B tokens only"
image="https://eastellar.com/images/MINT.png"

[[CURRENCIES]]
code="MAPLE"
issuer="GDKBXCWYC22TBGB2UU2S2KNHEI3YGNNAAO5XQGYQ7FHPKG2EKN7ASJG4"
status="live"
display_decimals=4
name="MAPLE"
fixed_number=25000000000
desc="MAPLE is issued by Eastellar Team."
conditions="Maximum supply of MAPLE is 25B tokens only"
image="https://eastellar.com/images/MAPLE.png"

[[CURRENCIES]]
code="BATz"
issuer="GC5QRGC3DBDVMQCXJ2XB4FDVXURG6S76536V36LXH6YEGRXEU2PH3XH6"
status="live"
display_decimals=4
name="BATz"
fixed_number=25000000000
desc="BATz is issued by Eastellar Team."
conditions="Maximum supply of BATz is 25B tokens only"
image="https://eastellar.com/images/BATz.png"