ACCOUNTS=[
"GA7UJMQTU6W36COR57SMGGUH66MORHHHHVX4WRQ7YOD2D724MTGBK3D7"
]

VERSION="1.0.0"

[DOCUMENTATION]
ORG_NAME="eastellar"
ORG_URL="https://www.eastellar.com/"
ORG_LOGO="https://www.eastellar.com/images/eastellar.png"
ORG_OFFICIAL_EMAIL="mail@eastellar.com"
ORG_TWITTER="eastellar"
ORG_DESCRIPTION="eastellar.com is a Stellar Assets Marketplace"
